sudo: false

language: go

go: 1.4

git:
  submodules: false

cache:
  directories:
    - hugo_0.15_linux_amd64
    - node_modules
  
before_install:
  - git submodule update --init --recursive --remote

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_linux_amd64.tar.gz
  - tar xzvf hugo_0.15_linux_amd64.tar.gz
  - chmod +x hugo_0.15_linux_amd64/hugo_0.15_linux_amd64
  - npm install

script:
  - chmod +x build_diagrams.sh deploy_ghpages.sh
  - ./build_diagrams.sh
  - grunt lunr-index
  - if [ $TRAVIS_BRANCH = master ]; then ./hugo_0.15_linux_amd64/hugo_0.15_linux_amd64 && echo seedstack.org >| public/CNAME && (curl -o public/distribution.pom.xml https://repo1.maven.org/maven2/org/seedstack/distribution/$SEEDSTACK_STABLE_VERSION/distribution-$SEEDSTACK_STABLE_VERSION.pom || :); fi
  - if [ $TRAVIS_BRANCH = beta ]; then ./hugo_0.15_linux_amd64/hugo_0.15_linux_amd64 -d beta -b http://beta.seedstack.org/ && echo beta.seedstack.org >| beta/CNAME && (curl -o beta/distribution.pom.xml https://repo1.maven.org/maven2/org/seedstack/distribution/$SEEDSTACK_BETA_VERSION/distribution-$SEEDSTACK_BETA_VERSION.pom || :); fi
  - if [ $TRAVIS_BRANCH = dev ]; then ./hugo_0.15_linux_amd64/hugo_0.15_linux_amd64 -d dev -b http://dev.seedstack.org/ && echo dev.seedstack.org >| dev/CNAME; fi

after_success:
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then ./deploy_ghpages.sh && (curl http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2Fseedstack.org%2Fsitemap.xml > /dev/null || :); fi
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = beta ]; then ./deploy_ghpages.sh beta; fi
  - if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = dev ]; then ./deploy_ghpages.sh dev; fi
