language: go

go: 1.4
  
notifications:
  irc: "chat.freenode.net#seedstack-dev"
  
install:
  - go get -v github.com/spf13/hugo
  - npm install

script:
  - chmod +x build_diagrams.sh deploy_ghpages.sh
  - ./build_diagrams.sh
  - hugo
  - grunt lunr-index
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" && $TRAVIS_BRANCH == \"master\" ]] && ./deploy_ghpages.sh"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" && $TRAVIS_BRANCH == \"master\" ]] && curl http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2Fwww.seedstack.org%2Fsitemap.xml > /dev/null"
