language: go

go: 1.4
  
notifications:
  irc: "chat.freenode.net#seedstack-dev"
  
install:
  - go get -v github.com/spf13/hugo
  - npm install

script:
  - chmod +x build_diagrams.sh deploy_ghpages.sh
  - ./build_diagrams.sh
  - hugo
  - grunt lunr-index
  - ./deploy_ghpages.sh
