language: go

go: 1.4
  
notifications:
  irc: "chat.freenode.net#seedstack-dev"
  
install: go get -v github.com/spf13/hugo

script: chmod +x build_diagrams.sh deploy_ghpages.sh && ./build_diagrams.sh && hugo && ./deploy_ghpages.sh
