baseurl = "http://seedstack.org/"
MetaDataFormat = "yaml"

[params]
  description = "Documentation of SeedStack, the lean development stack."
  author = "The SeedStack authors"
  "org.seedstack.seed.version" = "2.1.0"
  "org.seedstack.business.version" = "2.1.0"
  "org.seedstack.addons.audit.version" = "2.1.0"
  "org.seedstack.addons.elasticsearch.version" = "2.1.0"
  "org.seedstack.addons.i18n.version" = "2.1.0"
  "org.seedstack.addons.io.version" = "2.1.0"
  "org.seedstack.addons.javamail.version" = "2.1.0"
  "org.seedstack.addons.jcache.version" = "2.1.0"
  "org.seedstack.addons.jdbc.version" = "2.1.0"
  "org.seedstack.addons.jms.version" = "2.1.0"
  "org.seedstack.addons.jpa.version" = "2.1.0"
  "org.seedstack.addons.mongodb.version" = "1.0.0"
  "org.seedstack.addons.monitoring.version" = "2.1.0"
  "org.seedstack.addons.neo4j.version" = "1.0.0"
  "org.seedstack.addons.redis.version" = "1.0.0"
  "org.seedstack.addons.scheduling.version" = "2.1.0"
  "org.seedstack.addons.solr.version" = "1.0.0"
  "org.seedstack.addons.spring.version" = "2.1.0"
  "org.seedstack.addons.validation.version" = "2.1.0"
  "org.seedstack.addons.w20.version" = "2.1.0"
  "org.seedstack.addons.ws.version" = "2.1.0"

[blackfriday]
  angledQuotes = true
  plainIdAnchors = true

[taxonomies]
  tag = "tags"
  author = "authors"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Seed]
  path = "/docs/seed"
  label = "Java framework"
  logo = "seed-logo.svg"

[params.zone.Business]
  path = "/docs/business"
  label = "Business framework"
  logo = "business-logo.svg"

[params.zone.W20]
  path = "/docs/w20"
  label = "Web framework"
  logo = "w20-logo.svg"

[params.zone.GettingStarted]
  path = "/docs/getting-started"
  label = "Getting started"
  logo = "getting-started-logo.svg"

[params.zone.Glossary]
  path = "/docs/glossary"
  label = "Glossary"
  logo = "glossary-logo.svg"

[params.zone.Guides]
  path = "/guides"
  label = "Guides"
  logo = "guides-logo.svg"

[params.zone.Project]
  path = "/project"
  label = "Project"
  logo = "project-logo.svg"

[params.zone.Posts]
  path = "/posts"
  label = "Posts"
  logo = "blog-logo.svg"

[params.zone.Addons]
  path = "/addons"
  label = "Add-ons"
  logo = "addons-logo.svg"

[params.zone.Search]
  path = "/search"
  label = "Search"
  logo = "search-logo.svg"

#####################################
#### Project sections           ####
#####################################

[params.section.ProjectOverview]
  label = "Overview"
  icon = "fa fa-file-text"
  path = ""

[params.section.ProjectCommunity]
  label = "Community"
  icon = "fa fa-community"
  path = "community"

[params.section.ProjectFAQ]
  label = "FAQ"
  icon = "fa fa-comments-o"
  path = "faq"

[params.section.ProjectRoadmap]
  label = "Roadmap"
  icon = "fa fa-road"
  path = "roadmap"
    
[params.section.ProjectBuild]
  label = "Build"
  icon = "fa fa-cogs"
  path = ""

#####################################
#### Getting started sections    ####
#####################################

[params.section.GettingStartedIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.GettingStartedDistribution]
  label = "Distribution"
  icon = "fa fa-gift"
  path = "distribution"

[params.section.GettingStartedProjectTemplates]
  label = "Project templates"
  icon = "fa fa-cubes"
  path = "project-templates"

[params.section.GettingStartedTutorial]
  label = "Tutorial"
  icon = "fa fa-graduation-cap"
  path = "tutorial"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.BusinessManual]
  label = "Business manual"
  icon = "fa fa-book"
  path = "manual"

#####################################
#### Seed framework sections     ####
#####################################

[params.section.SeedIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.SeedManual]
  label = "Seed manual"
  icon = "fa fa-book"
  path = "manual"

[params.section.SeedMavenPlugin]
label = "Maven plugin"
icon = "fa fa-cogs"
path = "maven-plugin"

#####################################
#### W20 sections                ####
#####################################

[params.section.W20Introduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.W20Manual]
  label = "W20 manual"
  icon = "fa fa-book"
  path = "manual"

#####################################
#### Search                      ####
#####################################

[params.section.SearchResults]
  label = "Search results"
  icon = "fa fa-search"
  path = ""

