baseurl = "http://seedstack.org/"
MetaDataFormat = "yaml"

[params]
  description = "Documentation of SeedStack, a modular enterprise-class full development stack."
  author = "The SeedStack authors"

[blackfriday]
  angledQuotes = true
  plainIdAnchors = true

[taxonomies]
  tag = "tags"
  author = "authors"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Overview]
  path = "/Overview"
  label = "Overview"
  logo = "overview-logo.svg"

[params.zone.Seed]
  path = "/docs/seed"
  label = "Java framework"
  logo = "seed-logo.svg"

[params.zone.Business]
  path = "/docs/business"
  label = "Business framework"
  logo = "business-logo.svg"

[params.zone.W20]
  path = "/docs/w20"
  label = "Web framework"
  logo = "w20-logo.svg"

[params.zone.GettingStarted]
  path = "/docs/getting-started"
  label = "Getting started"
  logo = "getting-started-logo.svg"

[params.zone.Tools]
  path = "/docs/tools"
  label = "Tools"
  logo = "tools-logo.svg"

[params.zone.Samples]
  path = "/samples"
  label = "Samples"
  logo = "samples-logo.svg"

[params.zone.Glossary]
  path = "/docs/glossary"
  label = "Glossary"
  logo = "glossary-logo.svg"

[params.zone.Guides]
  path = "/guides"
  label = "Guides"
  logo = "guides-logo.svg"

[params.zone.Posts]
  path = "/posts"
  label = "Posts"
  logo = "blog-logo.svg"

[params.zone.Addons]
  path = "/addons"
  label = "Add-ons"
  logo = "addons-logo.svg"

[params.zone.Search]
  path = "/search"
  label = "Search"
  logo = "search-logo.svg"

#####################################
#### Overview sections           ####
#####################################

[params.section.OverviewIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.OverviewArchitecture]
  label = "Architecture"
  icon = "fa fa-building"
  path = ""

[params.section.OverviewCommunity]
  label = "Community"
  icon = "fa fa-community"
  path = ""

[params.section.OverviewRoadmap]
  label = "Roadmap"
  icon = "fa fa-road"
  path = ""
    
[params.section.OverviewFaq]
  label = "FAQ"
  icon = "fa fa-comments-o"
  path = ""

[params.section.OverviewBuild]
  label = "Build"
  icon = "fa fa-cogs"
  path = ""

#####################################
#### Getting started sections    ####
#####################################

[params.section.GettingStartedIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.GettingStartedDistribution]
  label = "Distribution"
  icon = "fa fa-gift"
  path = "distribution"

[params.section.GettingStartedProjectTypes]
  label = "Project types"
  icon = "fa fa-cubes"
  path = "project-types"

[params.section.GettingStartedTutorial]
  label = "Tutorial"
  icon = "fa fa-graduation-cap"
  path = "tutorial"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.BusinessConcepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"
  path = "concepts"

[params.section.BusinessManual]
  label = "Manual"
  icon = "fa fa-book"
  path = "manual"

[params.section.BusinessAPI]
  label = "API"
  icon = "fa fa-info"
  path = "api"

[params.section.BusinessReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

[params.section.BusinessCore]
  label = "Core"
  icon = "fa fa-cogs"
  path = "manual/core"

[params.section.BusinessEntity]
  label = "Entity"
  icon = "fa fa-square"
  path = "manual/entity"

[params.section.BusinessValueObject]
  label = "Value object"
  icon = "fa fa-square-o"
  path = "manual/value-object"

[params.section.BusinessAggregate]
  label = "Aggregate"
  icon = "fa fa-th-large"
  path = "manual/aggregate"

[params.section.BusinessFactory]
  label = "Factory"
  icon = "fa fa-magic"
  path = "manual/factory"

[params.section.BusinessRepository]
  label = "Repository"
  icon = "fa fa-archive"
  path = "manual/repository"

[params.section.BusinessService]
  label = "Service"
  icon = "fa fa-cog"
  path = "manual/service"

[params.section.BusinessEvent]
  label = "Domain event"
  icon = "fa fa-bolt"
  path = "manual/event"

[params.section.BusinessPolicy]
  label = "Policy"
  icon = "fa fa-legal"
  path = "manual/policy"

[params.section.BusinessAssembler]
  label = "Assembler"
  icon = "fa fa-arrows-h"
  path = "manual/assembler"

[params.section.BusinessFinder]
  label = "Finder"
  icon = "fa fa-search"
  path = "manual/finder"

[params.section.BusinessPagination]
  label = "Pagination"
  icon = "fa fa-file"
  path = "manual/pagination"

[params.section.BusinessRest]
  label = "REST"
  icon = "fa fa-link"
  path = "manual/rest"

[params.section.BusinessDataSecurity]
  label = "Data security"
  icon = "fa fa-shield"
  path = "manual/data-security"

[params.section.BusinessAudit]
  label = "Audit"
  icon = "fa fa-list"
  path = "manual/audit"

#####################################
#### Seed framework sections     ####
#####################################

[params.section.SeedIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.SeedConcepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"
  path = "concepts"

[params.section.SeedManual]
  label = "Manual"
  icon = "fa fa-book"
  path = "manual"

[params.section.SeedAPI]
  label = "API"
  icon = "fa fa-info"
  path = "api"

[params.section.SeedReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

[params.section.SeedCore]
  label = "Core"
  icon = "fa fa-cogs"
  path = "manual/core"

[params.section.SeedSecurity]
  label = "Security"
  icon = "fa fa-shield"
  path = "manual/security"

[params.section.SeedWeb]
  label = "Web"
  icon = "fa fa-globe"
  path = "manual/web"

[params.section.SeedRest]
  label = "Rest"
  icon = "fa fa-link"
  path = "manual/rest"

[params.section.SeedTransactions]
  label = "Transactions"
  icon = "fa fa-retweet"
  path = "manual/transactions"

[params.section.SeedPersistence]
  label = "Persistence"
  icon = "fa fa-database"
  path = "manual/persistence"

[params.section.SeedShell]
  label = "Shell"
  icon = "fa fa-terminal"
  path = "manual/shell"

[params.section.SeedTest]
  label = "Testing"
  icon = "fa fa-thumbs-up"
  path = "manual/testing"

[params.section.SeedMetrics]
  label = "Metrics"
  icon = "fa fa-chart"
  path = "manual/metrics"

#####################################
#### W20 sections                ####
#####################################

[params.section.W20Introduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.W20Concepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"
  path = "concepts"

[params.section.W20Manual]
  label = "Manual"
  icon = "fa fa-book"
  path = "manual"

[params.section.W20API]
  label = "API"
  icon = "fa fa-info"
  path = "api"

[params.section.W20ReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

[params.section.W20Core]
  label = "Core"
  icon = "fa fa-cogs"
  path = "manual/core"

[params.section.W20UI]
  label = "UI"
  icon = "fa fa-desktop"
  path = "manual/ui"

[params.section.W20Dataviz]
  label = "Data visualization"
  icon = "fa fa-bar-chart"
  path = "manual/dataviz"

[params.section.W20Extra]
  label = "Extras"
  icon = "fa fa-plus-square"
  path = "manual/extra"

#####################################
#### Tools                       ####
#####################################

[params.section.ToolsIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.ToolsMavenPlugin]
  label = "Maven plugin"
  icon = "fa fa-cogs"
  path = "maven-plugin"

#####################################
#### Search                      ####
#####################################

[params.section.SearchResults]
  label = "Search results"
  icon = "fa fa-search"
  path = ""

