baseurl = "http://seedstack.github.io/"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Seed]
  basepath = "/docs/seed"
  label = "Seed"

[params.zone.Business]
  basepath = "/docs/business"
  label = "Business"

[params.zone.W20]
  basepath = "/docs/w20"
  label = "W20"

[params.zone.GettingStarted]
  basepath = "/docs/getting-started"
  label = "Getting started"

[params.zone.Functions]
  basepath = "/docs/functions"
  label = "Reusable functions"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessDomainLayer]
  label = "Domain layer"
  icon = "fa fa-building"

[params.section.BusinessApplicationLayer]
  label = "Application layer"
  icon = "fa fa-cog"

[params.section.BusinessInterfaceLayer]
  label = "Interface layer"
  icon = "fa fa-th-large"

#####################################
#### Seed framework sections     ####
#####################################

[params.section.SeedCore]
  label = "Core"
  icon = "fa fa-cogs"

[params.section.SeedSecurity]
  label = "Security"
  icon = "fa fa-shield"

[params.section.SeedWeb]
  label = "Web"
  icon = "fa fa-globe"

[params.section.SeedRest]
  label = "Rest"
  icon = "fa fa-link"

[params.section.SeedTransactions]
  label = "Transactions"
  icon = "fa fa-retweet"

[params.section.SeedPersistence]
  label = "Persistence"
  icon = "fa fa-save"

[params.section.SeedJMS]
  label = "JMS"
  icon = "fa fa-random"

[params.section.SeedWebServices]
  label = "Web Services"
  icon = "fa fa-legal"

[params.section.SeedValidation]
  label = "Validation"
  icon = "fa fa-check"

[params.section.SeedSpring]
  label = "Spring"
  icon = "fa fa-leaf"

[params.section.SeedShell]
  label = "Shell"
  icon = "fa fa-terminal"

[params.section.SeedTest]
  label = "Testing"
  icon = "fa fa-thumbs-up"

[params.section.SeedBatch]
  label = "Batch"
  icon = "fa fa-file"

[params.section.SeedScheduling]
  label = "Scheduling"
  icon = "fa fa-clock-o"

[params.section.SeedCache]
  label = "Cache"
  icon = "fa fa-rocket"

[params.section.SeedMail]
  label = "Mail"
  icon = "fa fa-envelope"

[params.section.SeedMetrics]
  label = "Metrics"
  icon = "fa fa-chart"

#####################################
#### W20 sections                ####
#####################################

[params.section.W20Core]
  label = "Core"
  icon = "fa fa-cogs"

[params.section.W20UI]
  label = "UI"
  icon = "fa fa-desktop"

[params.section.W20Dataviz]
  label = "Data visualization"
  icon = "fa fa-bar-chart"

[params.section.W20Touch]
  label = "Touch"
  icon = "fa fa-hand-o-up"

[params.section.W20Extra]
  label = "Extras"
  icon = "fa fa-plus-square"

#####################################
#### Reusable functions sections ####
#####################################

[params.section.FunctionIO]
  label = "I/O"
  icon = "fa fa-file-text"

[params.section.FunctionI18n]
  label = "Internationalization"
  icon = "fa fa-comments"

[params.section.FunctionBridge]
  label = "W20 bridge"
  icon = "fa fa-link"