baseurl = "http://seedstack.github.io/"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Seed]
  basepath = "/docs/seed"
  label = "Seed"

[params.zone.Business]
  basepath = "/docs/business"
  label = "Business"

[params.zone.W20]
  basepath = "/docs/w20"
  label = "W20"

[params.zone.Functions]
  basepath = "/docs/functions"
  label = "Reusable functions"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessIntroduction]
  label = "Introduction"
  icon = "icon-signal"

[params.section.BusinessConcepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"

[params.section.BusinessReleaseNotes]
  label = "Release notes"
  icon = "icon-road"

[params.section.BusinessDomainLayer]
  label = "Domain layer"
  icon = "icon-building"

[params.section.BusinessApplicationLayer]
  label = "Application layer"
  icon = "icon-cog"

[params.section.BusinessInterfaceLayer]
  label = "Interface layer"
  icon = "icon-th-large"

#####################################
#### Seed framework sections     ####
#####################################

[params.section.SeedIntroduction]
  label = "Introduction"
  icon = "icon-file-text"

[params.section.SeedReleaseNotes]
  label = "Introduction"
  icon = "icon-file-text"

[params.section.SeedCore]
  label = "Core"
  icon = "icon-cogs"

[params.section.SeedSecurity]
  label = "Security"
  icon = "icon-shield"

[params.section.SeedWeb]
  label = "Web"
  icon = "icon-globe"

[params.section.SeedRest]
  label = "Rest"
  icon = "icon-link"

[params.section.SeedTransactions]
  label = "Transactions"
  icon = "icon-retweet"

[params.section.SeedPersistence]
  label = "Persistence"
  icon = "icon-save"

[params.section.SeedJMS]
  label = "JMS"
  icon = "icon-random"

[params.section.SeedWebServices]
  label = "Web Services"
  icon = "icon-legal"

[params.section.SeedValidation]
  label = "Validation"
  icon = "icon-check"

[params.section.SeedSpring]
  label = "Spring"
  icon = "icon-leaf"

[params.section.SeedShell]
  label = "Shell"
  icon = "icon-terminal"

[params.section.SeedTest]
  label = "Testing"
  icon = "icon-thumbs-up"

[params.section.SeedBatch]
  label = "Batch"
  icon = "icon-file"

[params.section.SeedScheduling]
  label = "Scheduling"
  icon = "icon-time"

[params.section.SeedCache]
  label = "Cache"
  icon = "icon-rocket"

[params.section.SeedMail]
  label = "Mail"
  icon = "icon-envelope"

[params.section.SeedMetrics]
  label = "Metrics"
  icon = "icon-chart"

#####################################
#### W20 sections                ####
#####################################

[params.section.W20Introduction]
  label = "Introduction"
  icon = "icon-file-text"

[params.section.W20Core]
  label = "Core"
  icon = "icon-cogs"

[params.section.W20UI]
  label = "UI"
  icon = "icon-desktop"

[params.section.W20Dataviz]
  label = "Dataviz"
  icon = "icon-chart"

[params.section.W20Touch]
  label = "Touch"
  icon = "icon-hand-up"

[params.section.W20Extra]
  label = "Extras"
  icon = "icon-plus-sign-alt"

[params.section.W20Guides]
  label = "Guides"
  icon = "icon-book"

[params.section.W20ReleaseNotes]
  label = "Release notes"
  icon = "icon-road"

#####################################
#### Reusable functions sections ####
#####################################

[params.section.FunctionIO]
  label = "I/O"
  icon = "icon-file-text"

[params.section.FunctionI18n]
  label = "Internationalization"
  icon = "icon-comments"

[params.section.FunctionBridge]
  label = "W20 bridge"
  icon = "icon-link"