baseurl = "http://gohugo.io/"
MetaDataFormat = "yaml"

[zone]
  seed = "/docs/seed/"
  business = "/docs/business/"
  w20 = "/docs/w20/"

[taxonomies]
  tag = "tags"
  zone = "zones"
  section = "sections"

[params.business.concepts]
  icon = "fa fa-lightbulb-o"
  label = "Concepts"
