baseurl = "http://seedstack.github.io/"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Seed]
  path = "/docs/seed"
  label = "Java framework"

[params.zone.Business]
  path = "/docs/business"
  label = "Business framework"

[params.zone.W20]
  path = "/docs/w20"
  label = "Web framework"

[params.zone.GettingStarted]
  path = "/docs/getting-started"
  label = "Getting started"

[params.zone.Tools]
  path = "/docs/tools"
  label = "Tools"

[params.zone.Guides]
  path = "/guides"
  label = "Guides"

[params.zone.Glossary]
  path = "/doc/glossary"
  label = "Glossary"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.BusinessConcepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"
  path = "concepts"

[params.section.BusinessReference]
  label = "Reference"
  icon = "fa fa-book"
  path = "reference"

[params.section.BusinessAPI]
  label = "API"
  icon = "fa fa-info"
  path = "api"

[params.section.BusinessReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

[params.section.BusinessEntity]
  label = "Entity"
  icon = "fa fa-square"
  path = "reference/entity"

[params.section.BusinessValueObject]
  label = "Value object"
  icon = "fa fa-square-o"
  path = "reference/value-object"

[params.section.BusinessAggregate]
  label = "Aggregate"
  icon = "fa fa-th-large"
  path = "reference/aggregate"

[params.section.BusinessFactory]
  label = "Factory"
  icon = "fa fa-magic"
  path = "reference/factory"

[params.section.BusinessRepository]
  label = "Repository"
  icon = "fa fa-archive"
  path = "reference/repository"

[params.section.BusinessService]
  label = "Service"
  icon = "fa fa-cog"
  path = "reference/service"

[params.section.BusinessEvent]
  label = "Domain event"
  icon = "fa fa-bolt"
  path = "reference/event"

[params.section.BusinessPolicy]
  label = "Policy"
  icon = "fa fa-legal"
  path = "reference/policy"

[params.section.BusinessAssembler]
  label = "Finder"
  icon = "fa fa-arrows-h"
  path = "reference/assembler"

[params.section.BusinessFinder]
  label = "Finder"
  icon = "fa fa-search"
  path = "reference/finder"

[params.section.BusinessPagination]
  label = "Pagination"
  icon = "fa fa-file"
  path = "reference/pagination"

[params.section.BusinessRest]
  label = "REST"
  icon = "fa fa-link"
  path = "reference/rest"

[params.section.BusinessDataSecurity]
  label = "Data security"
  icon = "fa fa-shield"
  path = "reference/data-security"

[params.section.BusinessAudit]
  label = "Audit"
  icon = "fa fa-list"
  path = "reference/audit"

#####################################
#### Seed framework sections     ####
#####################################

[params.section.SeedIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.SeedConcepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"
  path = "concepts"

[params.section.SeedReference]
  label = "Reference"
  icon = "fa fa-book"
  path = "reference"

[params.section.SeedAPI]
  label = "API"
  icon = "fa fa-info"
  path = "api"

[params.section.SeedReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

[params.section.SeedCore]
  label = "Core"
  icon = "fa fa-cogs"
  path = "reference/core"

[params.section.SeedSecurity]
  label = "Security"
  icon = "fa fa-shield"
  path = "reference/security"

[params.section.SeedWeb]
  label = "Web"
  icon = "fa fa-globe"
  path = "reference/web"

[params.section.SeedRest]
  label = "Rest"
  icon = "fa fa-link"
  path = "reference/rest"

[params.section.SeedTransactions]
  label = "Transactions"
  icon = "fa fa-retweet"
  path = "reference/transactions"

[params.section.SeedPersistence]
  label = "Persistence"
  icon = "fa fa-save"
  path = "reference/persistence"

[params.section.SeedJMS]
  label = "JMS"
  icon = "fa fa-random"
  path = "reference/jms"

[params.section.SeedWebServices]
  label = "Web Services"
  icon = "fa fa-legal"
  path = "reference/ws"

[params.section.SeedValidation]
  label = "Validation"
  icon = "fa fa-check"
  path = "reference/validation"

[params.section.SeedSpring]
  label = "Spring"
  icon = "fa fa-leaf"
  path = "reference/spring"

[params.section.SeedShell]
  label = "Shell"
  icon = "fa fa-terminal"
  path = "reference/shell"

[params.section.SeedTest]
  label = "Testing"
  icon = "fa fa-thumbs-up"
  path = "reference/test"

[params.section.SeedBatch]
  label = "Batch"
  icon = "fa fa-file"
  path = "reference/batch"

[params.section.SeedScheduling]
  label = "Scheduling"
  icon = "fa fa-clock-o"
  path = "reference/scheduling"

[params.section.SeedCache]
  label = "Cache"
  icon = "fa fa-rocket"
  path = "reference/cache"

[params.section.SeedMail]
  label = "Mail"
  icon = "fa fa-envelope"
  path = "reference/mail"

[params.section.SeedMetrics]
  label = "Metrics"
  icon = "fa fa-chart"
  path = "reference/metrics"

#####################################
#### W20 sections                ####
#####################################

[params.section.W20Introduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.W20Concepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"
  path = "concepts"

[params.section.W20Reference]
  label = "Reference"
  icon = "fa fa-book"
  path = "reference"

[params.section.W20API]
  label = "API"
  icon = "fa fa-info"
  path = "api"

[params.section.W20ReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

[params.section.W20Core]
  label = "Core"
  icon = "fa fa-cogs"
  path = "reference/core"

[params.section.W20UI]
  label = "UI"
  icon = "fa fa-desktop"
  path = "reference/ui"

[params.section.W20Dataviz]
  label = "Data visualization"
  icon = "fa fa-bar-chart"
  path = "reference/dataviz"

[params.section.W20Touch]
  label = "Touch"
  icon = "fa fa-hand-o-up"
  path = "reference/touch"

[params.section.W20Extra]
  label = "Extras"
  icon = "fa fa-plus-square"
  path = "reference/extra"

#####################################
#### Tools                       ####
#####################################

[params.section.ToolsIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.ToolsReference]
  label = "Reference"
  icon = "fa fa-book"
  path = "reference"

[params.section.ToolsReleaseNotes]
  label = "Release notes"
  icon = "fa fa-tag"
  path = "release-notes"

#####################################
#### Guides                      ####
#####################################

[params.section.CreateApplicationGuide]
  label = "Create a Web application"
  icon = "fa fa-globe"
  path = "create/web-application"

[params.section.CreateBatchGuide]
  label = "Create a batch"
  icon = "fa fa-file"
  path = "create/batch"

[params.section.CreateFunctionGuide]
  label = "Create a reusable function"
  icon = "fa fa-cogs"
  path = "create/reusable-function"

[params.section.CreateDomainGuide]
  label = "Create a domain"
  icon = "fa fa-cubes"
  path = "create/reusable-domain"


#####################################
#### Glossary                    ####
#####################################

[params.section.MainGlossary]
  label = "Glossary"
  icon = "fa fa-book"
  path = ""

#####################################
#### Reusable functions sections ####
#####################################

[params.section.FunctionIO]
  label = "I/O"
  icon = "fa fa-file-text"

[params.section.FunctionI18n]
  label = "Internationalization"
  icon = "fa fa-comments"

[params.section.FunctionBridge]
  label = "W20 bridge"
  icon = "fa fa-link"