baseurl = "http://seedstack.github.io/"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Seed]
  basepath = "/docs/seed/"
  label = "Seed"

[params.zone.Business]
  basepath = "/docs/business/"
  label = "Business"

[params.zone.W20]
  basepath = "/docs/w20/"
  label = "W20"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessIntroduction]
  label = "Introduction"
  icon = "icon-signal"

[params.section.BusinessConcepts]
  label = "Concepts"
  icon = "fa fa-lightbulb-o"

[params.section.BusinessReleaseNotes]
  label = "Release notes"
  icon = "icon-road"

[params.section.BusinessDomainLayer]
  label = "Domain layer"
  icon = "icon-building"

[params.section.BusinessApplicationLayer]
  label = "Application layer"
  icon = "icon-cog"

[params.section.BusinessInterfaceLayer]
  label = "Interface layer"
  icon = "icon-th-large"

#####################################
#### W20 sections                ####
#####################################

[params.section.W20Introduction]
  label = "Introduction"
  icon = "icon-file-text"

[params.section.W20Core]
  label = "Core"
  icon = "icon-cogs"

[params.section.W20UI]
  label = "UI"
  icon = "icon-desktop"

[params.section.W20Dataviz]
  label = "Dataviz"
  icon = "icon-chart"

[params.section.W20Touch]
  label = "Touch"
  icon = "icon-hand-up"

[params.section.W20Extra]
  label = "Extras"
  icon = "icon-plus-sign-alt"

[params.section.W20Guides]
  label = "Guides"
  icon = "icon-book"

[params.section.W20ReleaseNotes]
  label = "Release notes"
  icon = "icon-road"